### PR TITLE
update dev deps

### PR DESCRIPTION
**Pull request by dickeyxxx**
the code changes are all for standard@8

### CODE REVIEW

**Comment by uhoh-itsmaciek** [comment]
+1 🐫

**Comment by dickeyxxx** [comment]
unfortunately trying to update the main dependencies for this plugin wasn't as successful as the others... oh well

**Comment by uhoh-itsmaciek** [comment]
How so? Dare I ask?

**Comment by dickeyxxx** [comment]
ioredis seems to have changed significantly, also it uses the heroku-client directly which has changed quite a bit

**Comment by dickeyxxx** [comment]
I think updating ssh2 also caused problems but I didn't investigate much further

**Pull request merged**
