### PR TITLE
Use hiredis directly

### PR DESCRIPTION
**Pull request by cyberdelia**
It's fairly more straightforward, so that's a plus.

### CODE REVIEW

**Comment by dickeyxxx** [comment]
is this going to work on windows?

**Comment by cyberdelia** [comment]
According to the hiredis README:

```
Since Version 0.3.0 hiredis-node officially supports Windows. A simple npm install hiredis should just work. If not, please open a bug report.
```

But I can't really test.

**Comment by dickeyxxx** [comment]
I could test it, but it's kind of a pain. Probably won't get to it until after our off-site

**Comment by cyberdelia** [comment]
It probably can wait until then, huge thanks in advance for even trying.

**Comment by cyberdelia** [comment]
@dickeyxxx Did you can a chance to test this? You could win me making a standard-js PR for this plugin! 😃

**Comment by dickeyxxx** [comment]
bad news: 

```
HEAD is now at 6810cb0... Use hiredis directly

C:\Users\IEUser\redis>npm install
\
> hiredis@0.4.1 install C:\Users\IEUser\redis\node_modules\hiredis
> node-gyp rebuild


C:\Users\IEUser\redis\node_modules\hiredis>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:401:14)
gyp ERR! stack     at C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:356:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\IEUser\redis\node_modules\hiredis
gyp ERR! node -v v4.4.3
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE

npm ERR! hiredis@0.4.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hiredis@0.4.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the hiredis package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs hiredis
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls hiredis
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\IEUser\redis\npm-debug.log

C:\Users\IEUser\redis>
```

**Comment by dickeyxxx** [comment]
You might be able use hiredis conditionally, but users would always see this build failure

**Comment by dickeyxxx** [comment]
well, if they don't have python installed I guess

**Comment by cyberdelia** [comment]
😭 😭 😭 😭

**Comment by cyberdelia** [comment]
``node-gyp`` requires python, this is kinda sad.

**Pull request closed without merging**
